/**
 * build.js — generates config.js from environment variables.
 *
 * Local dev:  create .env.local with your Appwrite keys, then run: node build.js
 * Cloudflare: set APPWRITE_PROJECT_ID and APPWRITE_DATABASE_ID in Pages dashboard;
 *             build command is: node build.js
 */
const fs = require('fs');
const path = require('path');

// Load .env.local when present (local development)
const envPath = path.join(__dirname, '.env.local');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8')
    .split('\n')
    .forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;
      const eq = trimmed.indexOf('=');
      if (eq === -1) return;
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
      if (!process.env[key]) process.env[key] = val;
    });
}

const config = {
  appwriteEndpoint:  process.env.APPWRITE_ENDPOINT  || 'https://cloud.appwrite.io/v1',
  appwriteProjectId: process.env.APPWRITE_PROJECT_ID || 'DEMO',
  appwriteDatabaseId: process.env.APPWRITE_DATABASE_ID || 'DEMO',
};

const out = `// Auto-generated by build.js — do not edit or commit this file.\nwindow.APP_CONFIG = ${JSON.stringify(config)};\n`;
fs.writeFileSync(path.join(__dirname, 'config.js'), out);

const masked = config.appwriteProjectId !== 'DEMO'
  ? `project=${config.appwriteProjectId}  db=${config.appwriteDatabaseId}`
  : '(dev mode — DEMO values, localStorage only)';
console.log(`✓ config.js generated  →  ${masked}`);
