/**
 * build.js — generates dist/config.js from environment variables and copies
 *             index.html into dist/ so Cloudflare Pages only deploys those files.
 *
 * Local dev:  create .env.local with your Appwrite keys, then: node build.js
 * Cloudflare: set env vars in Pages dashboard; build command is: node build.js
 *             Build output directory: dist
 */
const fs   = require('fs');
const path = require('path');

// ── Load .env.local (local dev only) ───────────────────────
const envPath = path.join(__dirname, '.env.local');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
    const t = line.trim();
    if (!t || t.startsWith('#')) return;
    const eq = t.indexOf('=');
    if (eq === -1) return;
    const key = t.slice(0, eq).trim();
    const val = t.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    if (!process.env[key]) process.env[key] = val;
  });
}

// ── Build config ────────────────────────────────────────────
const config = {
  appwriteEndpoint:   process.env.APPWRITE_ENDPOINT   || 'https://cloud.appwrite.io/v1',
  appwriteProjectId:  process.env.APPWRITE_PROJECT_ID  || 'DEMO',
  appwriteDatabaseId: process.env.APPWRITE_DATABASE_ID || 'DEMO',
};

// ── Write output to dist/ ───────────────────────────────────
const dist = path.join(__dirname, 'dist');
if (!fs.existsSync(dist)) fs.mkdirSync(dist);

// config.js
const configOut = `// Auto-generated by build.js — do not edit.\nwindow.APP_CONFIG = ${JSON.stringify(config)};\n`;
fs.writeFileSync(path.join(dist, 'config.js'), configOut);

// copy static assets into dist
['index.html', 'icon.svg'].forEach(f => {
  const src = path.join(__dirname, f);
  if (fs.existsSync(src)) fs.copyFileSync(src, path.join(dist, f));
});

const masked = config.appwriteProjectId !== 'DEMO'
  ? `project=${config.appwriteProjectId}  db=${config.appwriteDatabaseId}`
  : '(DEMO mode — localStorage only)';
console.log(`✓ dist/ ready  →  ${masked}`);
