/**
 * build.js — generates dist/config.js from environment variables and copies
 *             index.html into dist/ so Cloudflare Pages only deploys those files.
 *
 * Local dev:  create .env.local with your Appwrite keys, then: node build.js
 * Cloudflare: set env vars in Pages dashboard; build command is: node build.js
 *             Build output directory: dist
 */
const fs   = require('fs');
const path = require('path');

// ── Load env files (precedence: process.env > .env.local > .env.example) ───
// .env.example is committed and holds the production Appwrite IDs (not secrets —
// they're sent in every browser API call). This lets Cloudflare Pages build
// correctly even without dashboard env vars configured.
function loadEnvFile(file) {
  const p = path.join(__dirname, file);
  if (!fs.existsSync(p)) return;
  fs.readFileSync(p, 'utf8').split('\n').forEach(line => {
    const t = line.trim();
    if (!t || t.startsWith('#')) return;
    const eq = t.indexOf('=');
    if (eq === -1) return;
    const key = t.slice(0, eq).trim();
    const val = t.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    const cur = process.env[key];
    // Treat empty values and obvious placeholders (your-project-id, etc.) as
    // unset so the next env file in precedence can supply a real value.
    if (!cur || /^your-/i.test(cur)) process.env[key] = val;
  });
}
loadEnvFile('.env.local');
loadEnvFile('.env.example');

// ── Build config ────────────────────────────────────────────
const config = {
  appwriteEndpoint:   process.env.APPWRITE_ENDPOINT   || 'https://cloud.appwrite.io/v1',
  appwriteProjectId:  process.env.APPWRITE_PROJECT_ID  || 'DEMO',
  appwriteDatabaseId: process.env.APPWRITE_DATABASE_ID || 'DEMO',
};

// ── Write output to dist/ ───────────────────────────────────
const dist = path.join(__dirname, 'dist');
if (!fs.existsSync(dist)) fs.mkdirSync(dist);

// config.js
const configOut = `// Auto-generated by build.js — do not edit.\nwindow.APP_CONFIG = ${JSON.stringify(config)};\n`;
fs.writeFileSync(path.join(dist, 'config.js'), configOut);

// copy static assets into dist
[
  'index.html',
  'icon.svg',
  'manifest.json',
  'apple-touch-icon.png',
  'favicon-32.png',
  'icon-192.png',
  'icon-512.png',
].forEach(f => {
  const src = path.join(__dirname, f);
  if (fs.existsSync(src)) fs.copyFileSync(src, path.join(dist, f));
});

const masked = config.appwriteProjectId !== 'DEMO'
  ? `project=${config.appwriteProjectId}  db=${config.appwriteDatabaseId}`
  : '(DEMO mode — localStorage only)';
console.log(`✓ dist/ ready  →  ${masked}`);
