-- ============================================================
--  Work Effort Tracker — Appwrite Collection Reference
--
--  Appwrite uses a GUI (or API) to create collections, not SQL.
--  This file documents the required collection structure.
--  Use it as a reference when setting up your Appwrite project.
-- ============================================================

-- DATABASE: create one database (e.g. "WorkTracker") in your Appwrite project.

-- COLLECTION: projects
-- Collection ID: projects  (set this exact ID when creating)
-- Attributes:
--   name       string   required  size:255
--   color      string   size:20   (hex colour, e.g. #3b82f6)
--   description string  size:1000
--   user_id    string   required  size:36
-- Indexes:
--   user_id_idx  key  attribute: user_id
-- Permissions:  Document-level security ON
--   (permissions are set per-document on create — see app code)

-- COLLECTION: customers
-- Collection ID: customers
-- Attributes:
--   name    string   required  size:255
--   type    string   required  size:20   (internal | external)
--   color   string   size:20
--   user_id string   required  size:36
-- Indexes:
--   user_id_idx  key  attribute: user_id

-- COLLECTION: entries
-- Collection ID: entries
-- Attributes:
--   title       string   required  size:500
--   project_id  string   size:36
--   customer_id string   size:36
--   hours       float    required  min:0
--   status      string   size:20   (pending | in-progress | completed)
--   date        string   size:20   (YYYY-MM-DD)
--   notes       string   size:2000
--   user_id     string   required  size:36
-- Indexes:
--   user_id_idx  key  attribute: user_id
--   date_idx     key  attribute: date
