-- ============================================================
--  Work Effort Tracker — PocketBase Collections Reference
--
--  PocketBase uses a GUI to create collections, not SQL.
--  This file documents the required collection structure.
--  Use it as a reference when setting up your PocketBase instance.
--
--  Quick setup: Import collections/schema_pb.json instead
--  (PocketBase Admin UI → Settings → Import collections)
-- ============================================================

-- COLLECTION: projects
-- Base type: Base
-- Fields:
--   name        text       required
--   color       text       (hex colour, e.g. #3b82f6)
--   description text
--   user        relation   → users collection, required
--
-- API Rules (access control):
--   List/Search : @request.auth.id = user
--   View        : @request.auth.id = user
--   Create      : @request.auth.id != ""
--   Update      : @request.auth.id = user
--   Delete      : @request.auth.id = user

-- COLLECTION: customers
-- Base type: Base
-- Fields:
--   name   text    required
--   type   select  options: internal, external  (required)
--   color  text    (hex colour)
--   user   relation → users collection, required
--
-- API Rules: same as projects

-- COLLECTION: entries
-- Base type: Base
-- Fields:
--   title       text    required
--   project_id  text    (stores PocketBase project record ID)
--   customer_id text    (stores PocketBase customer record ID)
--   hours       number  required, min: 0
--   status      select  options: pending, in-progress, completed
--   date        date
--   notes       text
--   user        relation → users collection, required
--
-- API Rules: same as projects
